[[HelloWorldCxx]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2744b6401a75d85707cdf3d2aba9b16298eb9bd5"
libc = "glibc"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "96954ca45023ec9c613454b600861bf6c40a615f07efa685f290c84632667498"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.0.3+0/HelloWorldCxx.v1.0.3.aarch64-linux-gnu-cxx03.tar.gz"
[[HelloWorldCxx]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "efea93da3cc12921423f5b5817b59e2cf0581fd8"
libc = "glibc"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "9c785a3ba5e87cd9ac6147e740c15c2fbd9b5c9f4165c169de8016b653baf77d"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.0.3+0/HelloWorldCxx.v1.0.3.aarch64-linux-gnu-cxx11.tar.gz"
[[HelloWorldCxx]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5ee8a76a0ab3d5dfd553256ca9f1c858a1b7da2a"
libc = "musl"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "29a6225dfe7ebb3e3d64a7fd39fd4752f4895e6d9b4d8dce107c2b64c7f631f8"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.0.3+0/HelloWorldCxx.v1.0.3.aarch64-linux-musl-cxx03.tar.gz"
[[HelloWorldCxx]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9d353038272a74cb91ccbb49bbd036e5dc65fc46"
libc = "musl"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "2499a34cf55f23e64d10457e102511a345090748cc8b81d89ccec595bb48b288"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.0.3+0/HelloWorldCxx.v1.0.3.aarch64-linux-musl-cxx11.tar.gz"
[[HelloWorldCxx]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6b2bba44b77c53bbf058a4f7536cd16712661f8a"
libc = "glibc"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "a3111cb57d97b9ed43032991bfbf28ee0e13a1770f8cfd4469e3307947683006"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.0.3+0/HelloWorldCxx.v1.0.3.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[HelloWorldCxx]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2b44d15fee1f8e74aa2a6be9b357a17a1f4403c8"
libc = "glibc"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "7f8e5d4d425cadb0bc13a98dcfa07c8dcc30c373504eb459bf50a99b1c1644cb"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.0.3+0/HelloWorldCxx.v1.0.3.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[HelloWorldCxx]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d6167b1a1b379aa439d32e4d3e2e673444458466"
libc = "musl"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "106c117104abdd32c6d7908884c3c0da761c9d7edcb4ee0db8fef99378c5842b"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.0.3+0/HelloWorldCxx.v1.0.3.armv7l-linux-musleabihf-cxx03.tar.gz"
[[HelloWorldCxx]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ed5c94470120748edc4ce2303d14560cbf9c816a"
libc = "musl"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "af357a5f92a2d59d0153798698c557b76589ac69b388ffb5c8eeffb90f477c0c"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.0.3+0/HelloWorldCxx.v1.0.3.armv7l-linux-musleabihf-cxx11.tar.gz"
[[HelloWorldCxx]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f73b602b8a847e182d139ed68ccbaf7f2deb5a66"
libc = "glibc"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "ec7daa0de526676f39b4eff4b2f459187bd0dba5a5c126d29963cb2d466a1624"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.0.3+0/HelloWorldCxx.v1.0.3.i686-linux-gnu-cxx03.tar.gz"
[[HelloWorldCxx]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d402b79ecebd70bf5de6d59005a81c82ebf9a5e0"
libc = "glibc"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "777a604c0c364686a4f49aa6db1884cb226bb7497448de39da2483ae7bec34ac"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.0.3+0/HelloWorldCxx.v1.0.3.i686-linux-gnu-cxx11.tar.gz"
[[HelloWorldCxx]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fdf55c18f91a62456ae57db8f55a37972fc8cf22"
libc = "musl"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "3122f0b585643287cfece255e48fdf968c92fb17fbb6fabd868d7dd1eddc8baa"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.0.3+0/HelloWorldCxx.v1.0.3.i686-linux-musl-cxx03.tar.gz"
[[HelloWorldCxx]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "792ac41e22bf7c802f695b91a233eb9620827798"
libc = "musl"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "a58ff0d0d9e86646e66b6d84c4170b1e808f397e565b48acf48912e813fe3a0d"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.0.3+0/HelloWorldCxx.v1.0.3.i686-linux-musl-cxx11.tar.gz"
[[HelloWorldCxx]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2d7704d57f0c740734bdaaa93bc0c2c6f4df265c"
os = "windows"

    [[HelloWorldCxx.download]]
    sha256 = "8b67af7010c4ec34ede5e00c696271273f32cd5f4d6bbc6ebc6517ba18021eb2"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.0.3+0/HelloWorldCxx.v1.0.3.i686-w64-mingw32-cxx03.tar.gz"
[[HelloWorldCxx]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dc8a331f23b8b5c676eaacedf4ba5004658df8cd"
os = "windows"

    [[HelloWorldCxx.download]]
    sha256 = "cad442432d1e2a8bd25ff7a42315f7863fa89965bb25bad44d894c6bdc661968"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.0.3+0/HelloWorldCxx.v1.0.3.i686-w64-mingw32-cxx11.tar.gz"
[[HelloWorldCxx]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2433a1c9f314f888d974eaea85f091cb6cd818c7"
libc = "glibc"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "060e9719d349a20deef855b21863e2202748ab7757daf45f6fd25a10e1c8d977"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.0.3+0/HelloWorldCxx.v1.0.3.powerpc64le-linux-gnu-cxx03.tar.gz"
[[HelloWorldCxx]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4534d4a403ee7028da74593d772e74073558bffa"
libc = "glibc"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "56470f3886bc7afd607d0baec2523f6f6065d6cb28233b596087fd1b07ea46fe"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.0.3+0/HelloWorldCxx.v1.0.3.powerpc64le-linux-gnu-cxx11.tar.gz"
[[HelloWorldCxx]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c3e0cdcce190e184c6ec28a5844940e37a38547d"
os = "macos"

    [[HelloWorldCxx.download]]
    sha256 = "9a7d7328c51fb8d6d49c8fdd6c8bdacc9da13a320aaf30c7d4f4ac230e60ef2c"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.0.3+0/HelloWorldCxx.v1.0.3.x86_64-apple-darwin14-cxx03.tar.gz"
[[HelloWorldCxx]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7a32558277ca4c536d3f1f72eb981750c2fef862"
os = "macos"

    [[HelloWorldCxx.download]]
    sha256 = "12c8d0c802428ab8d11ad386cc612f96340c01c851ee8660f9283f60584e5dcd"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.0.3+0/HelloWorldCxx.v1.0.3.x86_64-apple-darwin14-cxx11.tar.gz"
[[HelloWorldCxx]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "174102359b053237bda04c0367fd5b8f6f4bdec2"
libc = "glibc"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "e4155a8e389049d9833d91226bfeed9ac97fcf18b068f00f820f08f45bb43712"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.0.3+0/HelloWorldCxx.v1.0.3.x86_64-linux-gnu-cxx03.tar.gz"
[[HelloWorldCxx]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7f3c43de226d7729a7641dc469b5bac2e03a6542"
libc = "glibc"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "5fcced9ca5bf96eb24de673ff451afc0f66b6d2946b91266987833dc64c997a3"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.0.3+0/HelloWorldCxx.v1.0.3.x86_64-linux-gnu-cxx11.tar.gz"
[[HelloWorldCxx]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3534958f959f309b5b54186bc0b103daaf8d180f"
libc = "musl"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "e4a0b17af890baca1415cba805c832558747e1f2b4beef3565e2503021be9c6a"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.0.3+0/HelloWorldCxx.v1.0.3.x86_64-linux-musl-cxx03.tar.gz"
[[HelloWorldCxx]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "67a25bd10568ad00e34c7aa1da16ad0b3f9494ca"
libc = "musl"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "cb8ea2e05c68ae1164a17c5b6b3e8467bc046f52c127b7ff9283405c4124d5a7"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.0.3+0/HelloWorldCxx.v1.0.3.x86_64-linux-musl-cxx11.tar.gz"
[[HelloWorldCxx]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d5fba4201ce331387ef1a2c21c60c89f5ffd1931"
os = "freebsd"

    [[HelloWorldCxx.download]]
    sha256 = "356358ef553b348482c4cad9c8144c54db39dc052bb04085bf5d5c329defa87d"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.0.3+0/HelloWorldCxx.v1.0.3.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[HelloWorldCxx]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "48dee15121468872f8e15cc6cdee05f542eee60c"
os = "freebsd"

    [[HelloWorldCxx.download]]
    sha256 = "5e9b79e25f9bfe9a01fc77a46ba5e4c9a04d821faeba03e4fed155eeda7590ed"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.0.3+0/HelloWorldCxx.v1.0.3.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
[[HelloWorldCxx]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b3f15d6d33f08ce8fd3bae89055e3f6a4d5971ab"
os = "windows"

    [[HelloWorldCxx.download]]
    sha256 = "06c26569dd9e14bfb8f8f0398045eb29612c6a74e70c77ae386b5e0dfe4999ba"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.0.3+0/HelloWorldCxx.v1.0.3.x86_64-w64-mingw32-cxx03.tar.gz"
[[HelloWorldCxx]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "80052d7c7f9f6a603c2787f3a80cd3cd95895aa7"
os = "windows"

    [[HelloWorldCxx.download]]
    sha256 = "71bd1fc444f598023ad5b80adb7f58b4d0b2142eca8944baf104c6ee9c8912d8"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.0.3+0/HelloWorldCxx.v1.0.3.x86_64-w64-mingw32-cxx11.tar.gz"
