[[HelloWorldCxx]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "697584dc59e1d446e70e7320c8a3be85783beaff"
libc = "glibc"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "409a9b3fdee6721ea5bae94efe60eea6cc068b15dc9b43692c72edc61ad47037"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.0.0+0/HelloWorldCxx.v1.0.0.arm-linux-gnueabihf-cxx03.tar.gz"
[[HelloWorldCxx]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "81cb43c0d480a5f58f0ad963914fbb280cb875d4"
libc = "musl"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "93e62d80de54c9e1bf76f40732356b84a783f9f134037d9abf8c797aca490ef8"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.0.0+0/HelloWorldCxx.v1.0.0.arm-linux-musleabihf-cxx03.tar.gz"
[[HelloWorldCxx]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "16421ed2ea193f17a2d3e43abade4d11765c407f"
libc = "glibc"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "609354bdd62369f4cf1967f5bd1699a214fc0432bbf72b4b7e3a38a3d9ba274d"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.0.0+0/HelloWorldCxx.v1.0.0.arm-linux-gnueabihf-cxx11.tar.gz"
[[HelloWorldCxx]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5d1c2af1471724564f690fce72c11daeb5e4504e"
libc = "musl"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "bd0c4f7187c9cd380a0c4d2d0a741e56921e9dfa4118d8637ea22a927ba17914"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.0.0+0/HelloWorldCxx.v1.0.0.i686-linux-musl-cxx03.tar.gz"
[[HelloWorldCxx]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8734aa19bb4e130486a63c0f656b8affccbbc2fb"
libc = "musl"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "541235df63b30608b435e3decdeb6b73a78d623ae83d23e472a2283ecbebfb25"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.0.0+0/HelloWorldCxx.v1.0.0.i686-linux-musl-cxx11.tar.gz"
[[HelloWorldCxx]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4c0d6afa84e4eb24daf329a118230f305ff54789"
libc = "glibc"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "f61b03d0eec6e3cae445ad41d0f692fdcfb5ef955c09a6a82ebe5219865ade14"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.0.0+0/HelloWorldCxx.v1.0.0.i686-linux-gnu-cxx11.tar.gz"
[[HelloWorldCxx]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7e563b2ab907ee8c68764d1f124e18d0986a81fe"
libc = "glibc"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "7629df84f10e1d9aac03312ca0800ee0ed6ac312add7883d1eef0853103b5967"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.0.0+0/HelloWorldCxx.v1.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[HelloWorldCxx]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e4fdc91e541c251c9484e0356450163b4203a989"
os = "windows"

    [[HelloWorldCxx.download]]
    sha256 = "f186005ec00f0a93cce109edd42ecbb93e1abe7f11876348fbaf364ddf1b83da"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.0.0+0/HelloWorldCxx.v1.0.0.i686-w64-mingw32-cxx03.tar.gz"
[[HelloWorldCxx]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cae8d155411234addc789af8e9ce7f3a8681515a"
os = "windows"

    [[HelloWorldCxx.download]]
    sha256 = "88860517d67bef023dc3f9f21a9aff7bffaea4d06343936f4bdbdbfcfa785704"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.0.0+0/HelloWorldCxx.v1.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[HelloWorldCxx]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "da7a0c631e2ed17928648303b25bb6ca09019ec2"
libc = "glibc"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "bd4aa9ef30d5ddcf40e30d4bad6c8765302cc940914594a80eca48401db763f7"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.0.0+0/HelloWorldCxx.v1.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[HelloWorldCxx]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c55febce481af5e1d28eaf5e95c7f8467c780797"
libc = "musl"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "273e24e4ebc5ddbca64f9ed4d53dc1b7584082e0b5c9afa78d565ca538dd26ae"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.0.0+0/HelloWorldCxx.v1.0.0.aarch64-linux-musl-cxx11.tar.gz"
