[[HelloWorldCxx]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "95e912f7b9af4b5c68ba5bae47f450c611f346c1"
libc = "glibc"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "e745aa05ebd3782059ccccc13fd5ddf339818b54d75c04081a838a854fa70cdb"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.1.0+0/HelloWorldCxx.v1.1.0.aarch64-linux-gnu-cxx03.tar.gz"
[[HelloWorldCxx]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "193b2cf9525a09d4c7540c127255618f8809b14d"
libc = "glibc"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "e421956e12d531a7693dc1c9645a31db5b5a182cd799c9e9153ecf1e960fa424"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.1.0+0/HelloWorldCxx.v1.1.0.aarch64-linux-gnu-cxx11.tar.gz"
[[HelloWorldCxx]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e24762268f7a46a7f2e08df5d0c6b10fde4c3379"
libc = "musl"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "b6ebc9c5412e2ee6be8fe4bbb38c9e0714f2f3b35ff223a58f2c35774d6a3d79"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.1.0+0/HelloWorldCxx.v1.1.0.aarch64-linux-musl-cxx03.tar.gz"
[[HelloWorldCxx]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8ccfaa2d00e9fc3271bc6b20e38370496dc48e5d"
libc = "musl"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "a94c17d38f914bffa446d8ec52891feb3e2c041449c087de259d8f4517f357d5"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.1.0+0/HelloWorldCxx.v1.1.0.aarch64-linux-musl-cxx11.tar.gz"
[[HelloWorldCxx]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "540e8ce47ce1d655ac237ff4bd066614bab99d77"
libc = "glibc"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "72478128ed722da098afd75b111da15b1164e8d7d2e7cae5e8a856b1d2217d2b"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.1.0+0/HelloWorldCxx.v1.1.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[HelloWorldCxx]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1d9eb4b3ebeacedadfeb12f73158e04cc21f8221"
libc = "glibc"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "88e43a39e6c51bb41345b73cf9899283e94e2bad07aab988d73850a02c8e097e"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.1.0+0/HelloWorldCxx.v1.1.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[HelloWorldCxx]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f0fc6d32e5596c17064fe9e8e11964f13b1f1f9e"
libc = "musl"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "128c7da1803638bed918da83da495bb4d3c75ba1a4c5fab672e9debd08dd8935"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.1.0+0/HelloWorldCxx.v1.1.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[HelloWorldCxx]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e115ea0c72c70fbcc7117f3d0fbbc48f32da1921"
libc = "musl"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "1daf15fd4947f5d1d88c8557b1f3489e8dd0cc524de62232918f86209023a2cd"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.1.0+0/HelloWorldCxx.v1.1.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[HelloWorldCxx]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6568e5aa5cb247718b26201ae4380a5b40afca0a"
libc = "glibc"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "51d45abfc0113b270bc268d6288fb9b3d8af3369619ffa92e2f0f4af60b78e09"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.1.0+0/HelloWorldCxx.v1.1.0.i686-linux-gnu-cxx03.tar.gz"
[[HelloWorldCxx]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d618d8957702cbfe08f0f01b717efe31ca21daba"
libc = "glibc"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "90acd533cf6777ac018adeff2ff4728b319205e62b9b91f0009958b225f47dad"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.1.0+0/HelloWorldCxx.v1.1.0.i686-linux-gnu-cxx11.tar.gz"
[[HelloWorldCxx]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "229ed5ca9a8ce453ceef98043ffb0ede56850efa"
libc = "musl"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "4d43b68a2d2a19c8d44651fa023826eace81eaa2e50fa45ea4cf0b1541fb2298"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.1.0+0/HelloWorldCxx.v1.1.0.i686-linux-musl-cxx03.tar.gz"
[[HelloWorldCxx]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ae828212fe3a29895d73c7a3b29b39791e4d8ae2"
libc = "musl"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "e073ed05019a1ef659c9c35389eac8281bbd4a10a59655eb35ad941895474790"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.1.0+0/HelloWorldCxx.v1.1.0.i686-linux-musl-cxx11.tar.gz"
[[HelloWorldCxx]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ab948facb5aa55513818892f034f8539cac81c84"
os = "windows"

    [[HelloWorldCxx.download]]
    sha256 = "3f34f74f88789439e0ba7735d71d90ca6ea7eb5afc28ab8208d2521b35a71f9c"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.1.0+0/HelloWorldCxx.v1.1.0.i686-w64-mingw32-cxx03.tar.gz"
[[HelloWorldCxx]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0cb27059287157aa1804f8a065d13aa79aaaf260"
os = "windows"

    [[HelloWorldCxx.download]]
    sha256 = "f4faa42b5ea012737d17b0d376a80ddb12b28542f0ebb589de370e1ae41d671f"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.1.0+0/HelloWorldCxx.v1.1.0.i686-w64-mingw32-cxx11.tar.gz"
[[HelloWorldCxx]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d749a7567d0a64a79d80eb8a2a65ad6140e8ea41"
libc = "glibc"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "f41ab4428958aa6371f4aa09220bc25750ecdca77eef3d319b78ec052f8f47e4"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.1.0+0/HelloWorldCxx.v1.1.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[HelloWorldCxx]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a7b391e7901cd33f4b8a563ec4a81284d59ee964"
libc = "glibc"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "7fa596b1c02dbb7b448bf3c674c7450368d7dacc62d4b68d0ee10035c8dec727"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.1.0+0/HelloWorldCxx.v1.1.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[HelloWorldCxx]]
arch = "x86_64"
git-tree-sha1 = "c14852133424cf4f7b758b1ef2ddbb0fbfd4334f"
os = "macos"

    [[HelloWorldCxx.download]]
    sha256 = "d2a21fc905bc8e8b3e60f6b66997769b9384222ce14f99b5390f126ea98decaa"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.1.0+0/HelloWorldCxx.v1.1.0.x86_64-apple-darwin.tar.gz"
[[HelloWorldCxx]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4af1f7bf1e2ce349407b358c30c8af6fef0d957f"
libc = "glibc"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "f07e090e77148ce24e5dc187684e5a901db03622c04c303ed246aa3da4206900"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.1.0+0/HelloWorldCxx.v1.1.0.x86_64-linux-gnu-cxx03.tar.gz"
[[HelloWorldCxx]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "952ac621d3141989d114fe9b7201549eb1c4a046"
libc = "glibc"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "8e021a404bb3c0dfa553bc9fe3565a44516e75a893359cc3680c0afac160ca03"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.1.0+0/HelloWorldCxx.v1.1.0.x86_64-linux-gnu-cxx11.tar.gz"
[[HelloWorldCxx]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "94aefc48c25a8dc06bce14dc4dadb5bc7851cb50"
libc = "musl"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "3694aa494eb8aeb327f51094fc53c12de0b03f4fd14fbacfd776b7ce86b22de0"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.1.0+0/HelloWorldCxx.v1.1.0.x86_64-linux-musl-cxx03.tar.gz"
[[HelloWorldCxx]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b1c46fcab472debcb838ec4aada48c271ce350b7"
libc = "musl"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "08b42f3e68698e6244dc3d8480d363ac17355c752b87669469dac2edbf340f87"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.1.0+0/HelloWorldCxx.v1.1.0.x86_64-linux-musl-cxx11.tar.gz"
[[HelloWorldCxx]]
arch = "x86_64"
git-tree-sha1 = "64f9601fe49418ab7e54d8b436dba570b549f5b3"
os = "freebsd"

    [[HelloWorldCxx.download]]
    sha256 = "8d380d8fc5ff3ccb036ef2f8703f370c0be1d7630ff1b234f2b73a49ef804c8e"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.1.0+0/HelloWorldCxx.v1.1.0.x86_64-unknown-freebsd.tar.gz"
[[HelloWorldCxx]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "196d2f2d5cb77847f7ab5847e3f4ad3e846cfcb3"
os = "windows"

    [[HelloWorldCxx.download]]
    sha256 = "020b1b95b1544d1105a97e4a7b16e4ac9c63de53b0d3c5c155df325f0bcd17b7"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.1.0+0/HelloWorldCxx.v1.1.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[HelloWorldCxx]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "75afd3b06f50d48931e2a2d68d1de146b500a9ea"
os = "windows"

    [[HelloWorldCxx.download]]
    sha256 = "cbab334f76ae11d54977d335b1ed40016382981c02f76389977f87e2ad0c3461"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.1.0+0/HelloWorldCxx.v1.1.0.x86_64-w64-mingw32-cxx11.tar.gz"
