[[HelloWorldCxx]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7aaf0eb2e637effe711898ffffaaac384ae6fb36"
os = "macos"

    [[HelloWorldCxx.download]]
    sha256 = "6918232aa47f8c783a11db81c85d94f929ef44bfbf7f995542ea9041b21dc85f"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.0.0+0/HelloWorldCxx.v1.0.0.x86_64-apple-darwin14-cxx03.tar.gz"
[[HelloWorldCxx]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8ec07ae665b157018b26da2251f4864777110ad8"
libc = "glibc"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "0e134b1e7360227c75896675e87742e5216db072cefd6bf05ad2dd19f01ed0da"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.0.0+0/HelloWorldCxx.v1.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[HelloWorldCxx]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e9f19157eab3a59abd4dfd9f20c4c19268700003"
os = "windows"

    [[HelloWorldCxx.download]]
    sha256 = "45e1bf54a3d0cd6b857e1fdf97154d177feb00cb3e21c53286be4d56e84e9aa8"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.0.0+0/HelloWorldCxx.v1.0.0.i686-w64-mingw32-cxx03.tar.gz"
[[HelloWorldCxx]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a51a3a5e3830fa474133ed5c7163e5249b27b395"
libc = "musl"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "0798387346a3fbfca38f64df2a71698c1d25d5854077590210440463309f69f2"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.0.0+0/HelloWorldCxx.v1.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[HelloWorldCxx]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "46f13dc359caad63ea8378aaa36b6f7744ff730e"
libc = "musl"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "d40fc084aaf088fc682b92008d66af29ed500fc1542b341583415bb8db33fef4"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.0.0+0/HelloWorldCxx.v1.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[HelloWorldCxx]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6397b06f1e59308a4d2ee8442ca3eefec966071a"
libc = "glibc"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "a9f65a8797692cd102e618c014551ea048171142ead081e816745bc661db0db4"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.0.0+0/HelloWorldCxx.v1.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[HelloWorldCxx]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "88e409529465e1ae47cec5ecaa5a408717d61a68"
os = "windows"

    [[HelloWorldCxx.download]]
    sha256 = "14a4376e6cbda0e21c5bcc1719c51cee4defb9517394d484bff23ddc1922e3a3"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.0.0+0/HelloWorldCxx.v1.0.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[HelloWorldCxx]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "56092be6efdfe07d667ab9d3379ee15fcda3912e"
os = "windows"

    [[HelloWorldCxx.download]]
    sha256 = "cb7ca96b0a750d27abcbf35be863c5e7a4910988469c7d65db0bdb393e055a58"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.0.0+0/HelloWorldCxx.v1.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
[[HelloWorldCxx]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c2fac9bb48fe5fcf4d257fef1556c4686df09b7f"
os = "freebsd"

    [[HelloWorldCxx.download]]
    sha256 = "809407517fade9a776bb689d3a24e6bdaf636b52c0faf0eb4362ea9ffd31314c"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.0.0+0/HelloWorldCxx.v1.0.0.x86_64-unknown-freebsd11.1-cxx03.tar.gz"
[[HelloWorldCxx]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9ce9c8fdb82d52d19cbb0f0324d249cf9d3b0e7d"
os = "freebsd"

    [[HelloWorldCxx.download]]
    sha256 = "d81cef2da79685fd6f9a3411197d7cf0ae48e91e15658f1ae3fb3f9fd113c87a"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.0.0+0/HelloWorldCxx.v1.0.0.x86_64-unknown-freebsd11.1-cxx11.tar.gz"
