[[HelloWorldCxx]]
arch = "aarch64"
git-tree-sha1 = "292547a9a3bdfba3fce34a7b7ede75cadf0aa015"
os = "macos"

    [[HelloWorldCxx.download]]
    sha256 = "74e12af1b6b0a0bcb241741042bc2eae798d29d3d54ce62abd48e5fd4bf2fe5b"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.1.1+0/HelloWorldCxx.v1.1.1.aarch64-apple-darwin.tar.gz"
[[HelloWorldCxx]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8a7fbf1ec8ec09939ff0605837ff235336bde252"
libc = "glibc"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "dcf5184e6762fbc74b23e4686fa41f8f629e0bf364c3756467c0fe7e723681d3"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.1.1+0/HelloWorldCxx.v1.1.1.aarch64-linux-gnu-cxx03.tar.gz"
[[HelloWorldCxx]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1759ebc7310a1df34f5025e1c252074a5da6f74a"
libc = "glibc"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "d2f1b66751d30b0c2482cbd540e7bc9ec612fd19d86fc6bcb79e224a53c8e563"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.1.1+0/HelloWorldCxx.v1.1.1.aarch64-linux-gnu-cxx11.tar.gz"
[[HelloWorldCxx]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e86d9c9d15b165e376e53a7b43357d6bbd6fd45e"
libc = "musl"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "f19f5e8e79d5ff847059d8e899d4ada6bbdc09cf9ba03d4bbee28dd5c05f8963"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.1.1+0/HelloWorldCxx.v1.1.1.aarch64-linux-musl-cxx03.tar.gz"
[[HelloWorldCxx]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "57cb3df61c3ca922f0d6362f2c4e1d92cd9c8795"
libc = "musl"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "00897d9e995a5d654bce94c77ab576ab9c2db2574596306e86a3ab45a34fcc83"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.1.1+0/HelloWorldCxx.v1.1.1.aarch64-linux-musl-cxx11.tar.gz"
[[HelloWorldCxx]]
arch = "aarch64"
git-tree-sha1 = "6dbacc193553fd75c5cfa1e37e71c5d50228f775"
os = "freebsd"

    [[HelloWorldCxx.download]]
    sha256 = "ef8d02215beb242e80549e50ff4ae8fc63681ce9829e1ad14b675dbacbb44e26"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.1.1+0/HelloWorldCxx.v1.1.1.aarch64-unknown-freebsd.tar.gz"
[[HelloWorldCxx]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a3039fc0e44fea4ac45aea1ec9dd75feed4bc91c"
libc = "glibc"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "bbb1b4273ebe42cdcede064a97d7eb5e7bd0b2ee18ae5f1862c2b17a7e918c08"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.1.1+0/HelloWorldCxx.v1.1.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[HelloWorldCxx]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7f3157e43b518d73da9187bee30aef4e3aeb1972"
libc = "glibc"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "4d11f8501b8d7e2fe37ac404b82e3a527735e056cbb8ede96b195eb24214ccea"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.1.1+0/HelloWorldCxx.v1.1.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[HelloWorldCxx]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c045f77bac9eb5a7cd1d088927abc201aebd4458"
libc = "musl"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "d346fd097b865ff1303bfed44466444370458ddbfad5222fd66e10eedbe6db3e"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.1.1+0/HelloWorldCxx.v1.1.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[HelloWorldCxx]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "42b322c3434348857cf0893dd0d7bda7a4d42385"
libc = "musl"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "ce1ab87dce6ae65f2e3e7c73fc05d4ecfdd914b62653cbf69d79ee9e199542d4"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.1.1+0/HelloWorldCxx.v1.1.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[HelloWorldCxx]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "94adb624acff7211599ebae0e99b4d9256c48e25"
libc = "glibc"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "2ab002ff6eb4ac560654d12ea357e656a4f4eade40d784c7adfea288d41661f5"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.1.1+0/HelloWorldCxx.v1.1.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[HelloWorldCxx]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ac8cbcd68634f219d4d0767e5b509124e63abd06"
libc = "glibc"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "b44efed8b19a38556aef08adf1ae26cdbaef447eba1032aee8b064acf8180a90"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.1.1+0/HelloWorldCxx.v1.1.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[HelloWorldCxx]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "013dd3c7d4012bbff059a120f80481696b24c5e4"
libc = "musl"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "6f60218b576416d6e5d00e1bd10b5271536158d9aca64fcabe5eead74401d7f6"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.1.1+0/HelloWorldCxx.v1.1.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[HelloWorldCxx]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f266db150c2bf9bd517cf862539e68abb036f3c3"
libc = "musl"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "b04f81c9f42f020ab831ee713f26c7006c5eabc821c0ca8ed2d87f98d3e6e2e4"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.1.1+0/HelloWorldCxx.v1.1.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[HelloWorldCxx]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9350d126a5d6eaeabac5a335f8479253ba40b385"
libc = "glibc"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "d6c5be262f9a312ec96deb2dbf2886736752f1d3ceadcb96cdaec130952f1168"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.1.1+0/HelloWorldCxx.v1.1.1.i686-linux-gnu-cxx03.tar.gz"
[[HelloWorldCxx]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1aebc5c903e073e00b083104dc99f876a4be4ab6"
libc = "glibc"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "582dfcd564eadc51b3a96ebba3f74a69de4887154b6ac545fedef2138bfea7b7"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.1.1+0/HelloWorldCxx.v1.1.1.i686-linux-gnu-cxx11.tar.gz"
[[HelloWorldCxx]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a492414e04888b6f8322c623efae54e95878bb56"
libc = "musl"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "480082a5ba2badf031c8d593286f25d459c211b13b5882c0aa370bcb6ace7ce7"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.1.1+0/HelloWorldCxx.v1.1.1.i686-linux-musl-cxx03.tar.gz"
[[HelloWorldCxx]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0e71534a8225e6a561d3737705be39c646edacd5"
libc = "musl"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "8ee0e1914c5817a7f27ca8fe58de191d894679bda45d630b9dad89f9a070828c"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.1.1+0/HelloWorldCxx.v1.1.1.i686-linux-musl-cxx11.tar.gz"
[[HelloWorldCxx]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d663a86a2c2aa04430e1c36d4eaea76950d1291d"
os = "windows"

    [[HelloWorldCxx.download]]
    sha256 = "1cda13a98a9d65aaaabb94c1f67f87d4589c8cdc114b7f4d6278a5c9ebeff6ac"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.1.1+0/HelloWorldCxx.v1.1.1.i686-w64-mingw32-cxx03.tar.gz"
[[HelloWorldCxx]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d7ab5ce75330b34c16cdf8873d5d95aa426c02da"
os = "windows"

    [[HelloWorldCxx.download]]
    sha256 = "e2d98164422b7230832d18298d85e68a6aacd91ec2db127db545c2fe5b40a3d4"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.1.1+0/HelloWorldCxx.v1.1.1.i686-w64-mingw32-cxx11.tar.gz"
[[HelloWorldCxx]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "244190e2bc579208a7a7aea645168a21a472d5d3"
libc = "glibc"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "083307858f9cc3b081cb0afbaa05e45fb3244dea19035e763dc827f66da09ebd"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.1.1+0/HelloWorldCxx.v1.1.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[HelloWorldCxx]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "536d542cbd654cf4ecaf83912289779e06de66db"
libc = "glibc"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "c13928cd0610e23821b7f0e7a9d6897b7c2178fd293419768dee0fe7897e8f42"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.1.1+0/HelloWorldCxx.v1.1.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[HelloWorldCxx]]
arch = "x86_64"
git-tree-sha1 = "2b0cb4d99c2f2c17f848df3f9f2a49314c0939a7"
os = "macos"

    [[HelloWorldCxx.download]]
    sha256 = "a4ae673f4ad38c78cc39c08c3646d829f73b1591859682a5165a59792957e217"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.1.1+0/HelloWorldCxx.v1.1.1.x86_64-apple-darwin.tar.gz"
[[HelloWorldCxx]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4724d04cdbbc58d8a24f4a3f5a3bd569eaefabec"
libc = "glibc"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "599a86c03e6889a55b23080686be4016dfb1e27ccc0672d2266d0e17a339287e"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.1.1+0/HelloWorldCxx.v1.1.1.x86_64-linux-gnu-cxx03.tar.gz"
[[HelloWorldCxx]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "44883563eb9482145c7db0eb9a350f01bd0a2df9"
libc = "glibc"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "fc94374f79ed4a636a83d757ec13f2e280ce846477b5789e65bb02fbeb5dd431"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.1.1+0/HelloWorldCxx.v1.1.1.x86_64-linux-gnu-cxx11.tar.gz"
[[HelloWorldCxx]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ff48063de8042de1a494bb9f94f11a8cd6c8aa4e"
libc = "musl"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "16d810a1a77e44009b3158587fefe2a374261d59e288675bacc4db6954900170"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.1.1+0/HelloWorldCxx.v1.1.1.x86_64-linux-musl-cxx03.tar.gz"
[[HelloWorldCxx]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "26421e7eca1ef596984e36e9509c8aec845a3fee"
libc = "musl"
os = "linux"

    [[HelloWorldCxx.download]]
    sha256 = "6853f68704f977c3a4892b209f36d5e8ccf4eb13b72ce766b4d7de08cccad9f8"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.1.1+0/HelloWorldCxx.v1.1.1.x86_64-linux-musl-cxx11.tar.gz"
[[HelloWorldCxx]]
arch = "x86_64"
git-tree-sha1 = "801555405bc2cb6e70f3806264acf7d957a10f0a"
os = "freebsd"

    [[HelloWorldCxx.download]]
    sha256 = "72e78877bf9a314a607e84e0f6750acb319e364f5c48ece1c4f15404ec95d937"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.1.1+0/HelloWorldCxx.v1.1.1.x86_64-unknown-freebsd.tar.gz"
[[HelloWorldCxx]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f1c9f7571af751ecd26c25b26d28c3776b1a7586"
os = "windows"

    [[HelloWorldCxx.download]]
    sha256 = "510b3877e10f86e9daeb2c82b844060f9c08dd9158c6503eefca3d2f8609a299"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.1.1+0/HelloWorldCxx.v1.1.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[HelloWorldCxx]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "565e4b8926689b595a315ad5b97ad24570daa258"
os = "windows"

    [[HelloWorldCxx.download]]
    sha256 = "a35a90db438a587f6ae868d7e50a89783e13ef85a2ca55477100536066a7ab0e"
    url = "https://github.com/JuliaBinaryWrappers/HelloWorldCxx_jll.jl/releases/download/HelloWorldCxx-v1.1.1+0/HelloWorldCxx.v1.1.1.x86_64-w64-mingw32-cxx11.tar.gz"
